# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: '53 0 * * *'  # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox
        run: pipx install tox
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox
        run: pipx install tox
      - name: Run tests
        run: tox run -e unit


  # build:
  #   name: Build charms
  #   uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v29.0.0
  #   with:
  #     charmcraft-snap-channel: latest/candidate  # TODO: remove after charmcraft 3.3 stable release
  #     path-to-charm-directory: ${{ matrix.path }}
  #     cache: false  # TODO: fix after being added to ccc
  #   strategy:
  #     matrix:
  #       path:
  #         - .


  integration-test-vm:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - integration-mysql
          - integration-opensearch
          - integration-postgresql
          - integration-s3

    name: ${{ matrix.tox-environments }} (VM)
    needs:
      - lint
      - unit-test
    runs-on: ubuntu-22.04
    timeout-minutes: 240
    steps:
      - name: (GitHub hosted) Free up disk space
        timeout-minutes: 5
        run: |
          printf '\nDisk usage before cleanup\n'
          df --human-readable
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          rm -r /usr/share/dotnet
          rm -r /opt/hostedtoolcache/
          printf '\nDisk usage after cleanup\n'
          df --human-readable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3.6/stable
          bootstrap-options: "--agent-version 3.6.1"
      - name: Download packed charm(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi
      - name: Run integration tests
        run: |
          tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}'
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}


  integration-test-k8s:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - integration-mysql
          - integration-postgresql
          - integration-s3

    name: ${{ matrix.tox-environments }} (K8S)
    needs:
      - lint
      - unit-test
    runs-on: ubuntu-22.04
    timeout-minutes: 240
    steps:
      - name: (GitHub hosted) Free up disk space
        timeout-minutes: 5
        run: |
          printf '\nDisk usage before cleanup\n'
          df --human-readable
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          rm -r /usr/share/dotnet
          rm -r /opt/hostedtoolcache/
          printf '\nDisk usage after cleanup\n'
          df --human-readable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: "1.28-strict/stable"
          juju-channel: 3.6/stable
      - name: Download packed charm(s)
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi
      - name: Run integration tests
        run: tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}'
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}
          SUBSTRATE: k8s